config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	root "pages#index"
	get '/pages/show', to: 'pages#show'
	resources :users
	resources :posts
	get 'inquiry' => 'inquiry#index'              # 入力画面
	post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
	post 'inquiry/thanks' => 'inquiry#thanks'
	get 'contact', to: 'inquiry#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry
	include ActiveModel::Model

	attr_accessor :name, :email, :message

	validates :name, :presence => {:message =>'名前を入力してください'}
	validates :email, :presence => {:message =>'emailを入力してください'}
	
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :content, presence: true

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def contact
  end

  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end
 
  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end
 
  def thanks
    # メール送信
    @inquiry = Inquiry.new(inquiry_params)
    InquiryMailer.received_email(@inquiry).deliver
 
    # 完了画面を表示
    render :action => 'thanks'
  end


  private
  	def inquiry_params
  		params.require(:inquiry).permit(:name, :email, :message)
  	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
  end

  def show
    @posts = current_user.posts.all
  end

  def new
  	@post = current_user.posts.new
  end

  def create
  	@post = Post.new(post_params)
  	if @post.save
  		flash[:notice] = 'あなたはこのゴールを達成している'
  		redirect_to post_path(current_user)
   	else
   		# render plain: @post.errors.inspect
   		render 'new'
  	end
  end

  def edit
  	@post = current_user.posts.find(params[:id])
  end

  def update
  	@post = current_user.posts.find(params[:id])
  	if @post.update(post_params)
  		flash[:notice] = '編集が完了しました'
      redirect_to post_path(current_user)
  		# redirect_to user_path(@post.user)
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@post = current_user.posts.find(params[:id])
  	@post.destroy
  	flash[:notice] = '焦らずじっくりゴールを達成していきましょう'
  	redirect_to post_path(current_user)
  end

  private
  	def post_params
  		params.require(:post).permit(:content, :user_id, :image)
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/inquiry/confirm.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>
 
<%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
  <table class="table">
    <tr>
      <th>名前</th>
      <td>
        <%= f.hidden_field :name %>
        <%= @inquiry.name %>
      </td>
    </tr>
		<tr>
      <th>メールアドレス</th>
      <td>
        <%= f.hidden_field :email %>
        <%= @inquiry.email %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td>
        <%= f.hidden_field :message %>
        <%= simple_format(@inquiry.message) %>
      </td>
    </tr>
  </table>
  <%= f.submit '送信', :class => 'btn btn-primary' %>
<% end %>

app/views/inquiry/contact.html.erb
<div class="container">
  <div class="row text-center justify-content-center">
    <div class="col-md-6 col-md-offset-3 text-center">
      <h2>意見・要望を送る</h2>
      <form action="https://formspree.io/greatmotio@gmail.com" method="POST">
        <div class="form-group">
        <!--  <label for="name">Name</label> -->
          <input type="text" class="form-control" name="name" id="name" placeholder="Name">
        </div>
        <div class="form-group">
        <!--  <label for="email">Email Address</label> -->
          <input type="email" class="form-control" name="email" id="email" placeholder="Email Address">
        </div>
        <div class="form-group">
        <!--    <label for="message">Message</label> -->
          <textarea name="message" cols="40" rows="10" class="form-control" id="message" placeholder="Message"></textarea>
        </div>
      <button type="submit" class="btn btn-primary">送信</button>
      </form>
    </div>
  </div>   
</div>

app/views/inquiry/index.html.erb
<%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
  <div class="page-header">
    <h1>お問い合わせ</h1>
  </div>
 
  <% if @inquiry.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <strong>入力内容にエラーがあります</strong>
      <ul>
        <% @inquiry.errors.each do |attr, msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <table class="table">
    <tr>
      <th>名前<span class="text-danger">（必須）</span></th>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <th>メールアドレス<span class="text-danger">（必須）</span></th>
      <td><%= f.text_field :email %></td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td><%= f.text_area :message %></td>
    </tr>
  </table>
  <%= f.submit '確認', class: 'btn btn-primary' %>
<% end %>

app/views/inquiry/thanks.html.erb
<div class="page-header">
	<h1>お問い合わせ</h1>
</div>

<p>
	お問い合わせありがとうございました。
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>UdemyS01</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
  <% unless flash.empty? %>
    <script type="text/javascript">
      <% flash.each do |f| %>
        <% type = f[0].to_s.gsub('alert','error').gsub('notice', 'info') %>
        toastr['<%= type %>']('<%= f[1] %>');
      <% end %>
    </script>
  <% end %>

  <footer>
    <ul>
      <li>Cinderella</li>
    </ul>
  </footer>
</body>
</html>

app/views/pages/index.html.erb
<%= render 'partial/navbar' %>

<div class="jumbotron">

　<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 text-center">
			<h1>人生を変える〜アファメーション〜</h1>
		</div>
	</div>
　</div> <!-- /container -->    
</div>

app/views/pages/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 text-center">
			<div class="Codetank-20170108 Codetank__source">
				<button id="action-20170210">START</button>
				<div class="case-transform moving-box-lo">
					<div class="moving-box-lo__mod"></div>
				</div>
			</div>

			<p>あなたは目標を達成する！</p>
			<p>あなたは無限の潜在能力を使っている！</p>
			<p>あなたは毎日どんどん豊かになっている！</p>	

			<%= link_to 'affirmation', user_path(current_user) %>
		</div>
	</div>
</div>

app/views/partial/_deviseErrorMsg.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>');
		<% end %>
	</script>
<% end %>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-default navbar-custom">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Yes!! You can!!</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
      	<% if !user_signed_in? %>
          <li><%= link_to 'Yes!! You can!!に関して', '#' %></li>
          <li><%= link_to 'アファメーションとは', '#' %></li>
	        <li><%= link_to 'アカウント作成', new_user_registration_path %></li>
	        <li><%= link_to 'ログイン', new_user_session_path %></li>
	      <% else %>
          <li><%= link_to '使い方', '#' %></li>
          <li><%= link_to 'アファメーションの作り方', '#' %></li>
	      	<li><%= link_to 'あなたのゴール設定', post_path(current_user) %></li>
	      	<li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      	<% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<p>
		<%= f.text_area :content, placeholder: 'ゴールを入力してください' %>
		<% if @post.errors.messages[:content].any? %>
		<%= @post.errors.messages[:content][0] %>
		<% end %>
	</p>

	<p>
		<%= f.file_field :image %>
	</p>

	<p>
		<%= f.hidden_field :user_id %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/posts/edit.html.erb
<%= render 'partial/navbar' %>

<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 text-center">
			<h2>ゴールを編集する</h2>

			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<h2>あなたはゴールを達成する</h2>

<%= link_to 'ゴールを追加する', new_post_path %>

<ul>
		<% @posts.each do |post| %>
			<li><%= post.content %><%= post.user_id %></li>
		<% end %>
</ul>

app/views/posts/new.html.erb
<%= render 'partial/navbar' %>

<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 text-center">
			<h2>ゴールを追加する</h2>

			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<%= render 'partial/navbar' %>

<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 text-center">

			<h2>ゴールを設定する</h2>

			<p>
				<input type="button" onclick="location.href='http://localhost:3000/pages/show'"value="アファメーションに進む">
			</p>

			<div>
				<%= link_to 'ゴールを追加する', new_post_path(@user) %>	
			</div>

			<ul>
				<% @posts.each do |post| %>
					<li class="space"><%= post.content %></li>
					<li>
						<% if post.image? %>
							<%= image_tag post.image.url %>
						<% end %>
					</li>
					<%= link_to '[編集]', edit_post_path(post) %>
						<%= link_to '[削除]', post_path(post), method: :delete, data: {confirm: '削除してよろしいですか？'} %>
					<% end %>
			</ul>

			<p>
				<input type="button" onclick="location.href='http://localhost:3000/pages/show'"value="アファメーションに進む">
			</p>
		</div>
	</div>
</div>

<!-- これだとURLは合っているのにNoRouteエラーが出る -->

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 text-center">
			<ul>
				<div class="space">
					<% @user.posts.each do |post| %>
						<li class="space"><%= post.content %></li>
						<li>
							<% if post.image? %>
								<%= image_tag post.image.url %>
							<% end %>
						</li>
					<% end %>
				</div>
			</ul>
		</div>
	</div>
</div>